name: Build Android App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Restore Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > upload-keystore.jks

      - name: Build Android Bundle
        env:
          KEY_PASS: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          cordova platform rm android || true
          cordova platform add android@15.0.0

          cordova build android --release -- --bundle \
            --keystore=upload-keystore.jks \
            --storePassword="$KEY_PASS" \
            --password="$KEY_PASS" \
            --alias="$ALIAS"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: platforms/android/app/build/outputs/bundle/release/*.aab
